server.port: 8080
spring:
  application.name: zenorger
  main.banner-mode: console
  jackson.default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5433/serdtsev
    username: serdtsev
    password: serdtsev
    default-auto-commit: false
  jpa:
    properties:
      hibernate:
        default_schema: zenorger
        ddl-auto: validate
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
        use_query_cache: true
        jdbc.lob.non_contextual_creation: true
        format_sql: false
    open-in-view: true
    show-sql: false
  liquibase:
    default-schema: zenorger
    change-log: classpath:db/changelog/spring.liquibase.change-log.sql

logging.config: ./config/logback-spring.xml

springfox.documentation.swagger.v2.path: /v2/api-docs
