server.port: 8080
spring:
  application.name: zenorger
  main.banner-mode: console
  jackson.default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari.auto-commit: false
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
        use_query_cache: true
        jdbc.lob.non_contextual_creation: true
        format_sql: false
    open-in-view: true
    show-sql: false

logging.config: ./config/logback-spring.xml

springfox.documentation.swagger.v2.path: /v2/api-docs
